export default [
    {
        seq : 1,
        name : '라이언',
        kor : 76,
        eng : 57,
        math : 68,
        tot : 0,
        avg : 0,
    },
    {
        seq : 2,
        name : '춘식이',
        kor : 50,
        eng : 70,
        math : 50,
        tot : 0,
        avg : 0,
    },
    {
        seq : 3,
        name : '어피치',
        kor : 30,
        eng : 50,
        math : 70,
        tot : 0,
        avg : 0,
    },
    {
        seq : 4,
        name : '프로도',
        kor : 90,
        eng : 80,
        math : 77,
        tot : 0,
        avg : 0,
    },
    {
        seq : 5,
        name : '무지',
        kor : 77,
        eng : 55,
        math : 66,
        tot : 0,
        avg : 0,
    },
]